#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build

docker-compose run --rm rails rails new . --force --database=postgresql --skip-bundle --skip-git --skip-test --webpack && bundle update
# docker-compose run --rm rails rails webpacker:install:react

cp -f template/database.yml config/database.yml
cp -f template/webpacker.yml config/webpacker.yml
cp -f template/gitignore .gitignore

docker-compose run --rm rails bundle exec spring binstub --all
